#!/usr/bin/env bash

: ${TQL_HOME:=$HOME/tql}
source $TQL_HOME/db_functions

shouldHelpOrExecute "$1" $#; declare -i helpCode=$?
if ((helpCode)); then
    giveHelp "$0" $helpCode columns
    doExit
fi

readMetadataAndConfigure "$0" columns || doExit

# Parse the TQL and generate the SQL
parseCompletely "$@" || doExit
getReturnValues OPTIONS ACTION_CLAUSE WHERE_CLAUSE LIMIT sortInstructions queryType
formQuery $queryType "$ACTION_CLAUSE" "$WHERE_CLAUSE" "$LIMIT"
getReturnValue fullQuery

# Display the query if requested
isOptionOn "q|query" $OPTIONS
if (($?)); then
    setError ${rc[SUCCESS]}
    doExit "$fullQuery"
fi

# Execute the query
if ! RAW_RESULT=$("${TQL_DB_WRAPPER:-mysql}" $g_dbClientOptions -t -e "$fullQuery"); then
    setError $?; doExit "Error running query."
fi

# For SELECT queries, display the result set
if [[ $queryType == ${qt[SELECT]} ]]; then
    formatResultSet "$RAW_RESULT" "$sortInstructions"; getReturnValue formattedResult
    echo "$formattedResult"
fi
doExit

