#!/usr/bin/env bash

: ${TQL_HOME:=$HOME/tql}
source $TQL_HOME/db_functions

THIS_SCRIPT=`basename $0`
validate_single_column "$@"

STANDARD_COLS="DISTINCT table_name,column_name"
# Other useful cols: column_type, column_key, ordinal_precision, column_default, data_type
TABLES="information_schema.columns"
WHERE_PRECLAUSE="table_schema='$TQL_DBNAME' and table_name not like '%view%'"

# Column name inference rules
g_defaultAlnums=column_name

# Invoke the main parsing routine
parseCompletely  "$STANDARD_COLS"  "$TABLES"  "column_name"  "$WHERE_PRECLAUSE"  "$@"
retVal=$?
if ((retVal >= 10)); then
    echo Exiting.
    exit $retVal
elif ((retVal == 1)); then
    g_ACTION=UPDATE
fi

getReturnValues  OPTIONS  ACTION_CLAUSE  WHERE_CLAUSE  LIMIT  sortInstructions

if [[ $g_ACTION == UPDATE ]]; then
    DB_COMMAND="$g_ACTION $TABLES $ACTION_CLAUSE $WHERE_CLAUSE $LIMIT"
else
    DB_COMMAND="$g_ACTION $ACTION_CLAUSE FROM $TABLES $WHERE_CLAUSE $LIMIT"
fi

isOptionOn "q|query" $OPTIONS
if (($?)); then
    echo "$DB_COMMAND"
    exit 0
fi

RAW_RESULT=$("${TQL_DB_WRAPPER:-mysql}" $g_dbClientOptions -t -e "$DB_COMMAND") || exit $?
if [[ $g_ACTION == UPDATE ]]; then exit 0; fi

if [[ -z $RAW_RESULT ]]; then
    echo No Columns found. > /dev/stderr
    exit 1
fi

foldResultSet "$RAW_RESULT" "$sortInstructions"

