#!/usr/bin/env bash

: ${TQL_HOME:=$HOME/tql}
source $TQL_HOME/db_functions

shouldHelpOrExecute "$1" $#; declare -i helpCode=$?
if ((helpCode)); then
    giveHelp "$0" $helpCode tables " "
    doExit
fi

STANDARD_COLS="t.table_name as table_name,column_name,auto_increment"
TABLES="information_schema.tables t,information_schema.columns c"      # A table join is needed because auto_increment is from t and column_name is from c
WHERE_PRECLAUSE="t.table_name=c.table_name AND t.table_schema=c.table_schema AND t.table_schema='"$TQL_DBNAME"'"  # TQL_DBNAME uniqifies the result set if there are multiple DBs

g_defaultAlnums=t.table_name

# Invoke the main parsing routine to manage cmdline options and different forms of table-name arguments.
parseCompletely  "$STANDARD_COLS"  "$TABLES"  ""  "$WHERE_PRECLAUSE"  "$@"
retVal=$?
if ((retVal >= 10)); then
    echo Exiting.
    exit $retVal
fi

getReturnValues  OPTIONS  ACTION_CLAUSE  WHERE_CLAUSE  LIMIT  sortInstructions

WHERE_CLAUSE+=" AND c.extra='auto_increment'"

DB_COMMAND="$g_ACTION $ACTION_CLAUSE FROM $TABLES $WHERE_CLAUSE"

isOptionOn "q|query" $OPTIONS
if (($?)); then
    echo "$DB_COMMAND"
    exit 0
fi

RAW_RESULT=$("${TQL_DB_WRAPPER:-mysql}" $g_dbClientOptions -t -e "$DB_COMMAND") || exit $?

foldResultSet "$RAW_RESULT" "$sortInstructions"

