#!/usr/bin/env bash

: ${TQL_HOME:=$HOME/tql}
source $TQL_HOME/db_functions

shouldHelpOrExecute "$1" $#; declare -i helpCode=$?
if ((helpCode)); then
    giveHelp "$0" $helpCode table
    doExit
fi

# Ensure canonical syntax: main table name as the first positional parameter
local parameters
swapValueParameterToFront "$@" && getReturnValue parameters || doExit
eval set -- $parameters

readSchemaAndConfigure "$1" || doExit
shift

# Parse the TQL and generate the SQL
parseCompletely "$@" || doExit
getReturnValues OPTIONS ACTION_CLAUSE WHERE_CLAUSE LIMIT sortInstructions queryType
formQuery $queryType "$ACTION_CLAUSE" "$WHERE_CLAUSE" "$LIMIT"
getReturnValue fullQuery

# Display the query if requested
isOptionOn "q|query" $OPTIONS
if (($?)); then
    setError ${rc[SUCCESS]} "$fullQuery"
    doExit
fi

# Execute the query
if ! RAW_RESULT=$("${TQL_DB_WRAPPER:-mysql}" $g_dbClientOptions -t -e "$fullQuery"); then
    setError $?; doExit "Error running query."
fi

# For SELECT queries, display the result set
if [[ $queryType == ${qt[SELECT]} ]]; then
    foldResultSet "$RAW_RESULT" "$sortInstructions"
fi
doExit

