#!/usr/bin/env bash

: ${TQL_HOME:=$HOME/tql}
source $TQL_HOME/db_functions

shouldHelpOrExecute "$1" $#; declare -i helpCode=$?
if ((helpCode)); then
    giveHelp "$0" $helpCode tables " "
    doExit
fi

readMetadataAndConfigure "$0" tables || doExit

# Invoke the main parsing routine to manage cmdline options and different forms of table-name arguments.
# This script's configuration limits the flexibility of the query.
parseCompletely "$@" || doExit
getReturnValues  OPTIONS  ACTION_CLAUSE  WHERE_CLAUSE  LIMIT  sortInstructions queryType
formQuery $queryType "${g_config[standardColumns]}" "$WHERE_CLAUSE" ""
getReturnValue fullQuery

isOptionOn "q|query" $OPTIONS
if (($?)); then
    setError ${rc[SUCCESS]}
    doExit "$fullQuery"
fi

# Execute the query
if ! RAW_RESULT=$("${TQL_DB_WRAPPER:-mysql}" $g_dbClientOptions -t -e "$DB_COMMAND"); then
    setError $?; doExit "Error running query."
fi

# Since this is a SELECT query, display the result
formatResultSet "$RAW_RESULT" "$sortInstructions"; getReturnValue formattedResult
echo "$formattedResult"
doExit

